apiVersion: v1alpha1
kind: Setting
metadata:
  name: plugin-webhook-settings
spec:
  forms:
    - group: basic
      label: 设置
      formSchema:
        - $formkit: radio
          name: enableWebhook
          id: enableWebhook
          label: 是否启用webhook
          value: false
          options:
            - label: 启用
              value: true
            - label: 关闭
              value: false
        - $formkit: url
          if: $get(enableWebhook).value
          name: webhookUrl
          label: webhook地址
          help: 当产生事件时会向该地址推送消息
          placeholder: https://www.example.com...
          validation: required|url
          value: