apiVersion: plugin.halo.run/v1alpha1
kind: Plugin
metadata:
  name: wxyshine-webhook
spec:
  enabled: true
  requires: ">=2.11.0"
  author:
    name: www.wxy97.com
    website: https://www.wxy97.com
  logo: logo.png
  homepage: https://github.com/halo-dev/plugin-starter
  displayName: "Webhook"
  description: "为Halo提供webhook支持"
  settingName: plugin-webhook-settings
  configMapName: plugin-webhook-configMap
  license:
    - name: "GPL-3.0"
      url: "https://github.com/halo-dev/plugin-starter/blob/main/LICENSE"
